print("Hello World")
print("ABCD")
print("Anirudh Khurana is a good coder abcde fghij lmno")
print("Exit")

physics = int(input("Enter marks in physics = "))
chemistry = int(input("Enter marks in chemistry = "))
maths = int(input("Enter marks in maths = "))
english = int(input("Enter marks in english = "))
hindi = int(input("Enter marks in hindi = "))
